/* Router registry — mounts every domain router under /api. */
const { Router } = require('express')

const authRoutes = require('./auth.routes')
const patientRoutes = require('./patient.routes')
const visitRoutes = require('./visit.routes')
const vitalsRoutes = require('./vitals.routes')
const admissionRoutes = require('./admission.routes')
const activityRoutes = require('./activity.routes')
const investigationRoutes = require('./investigation.routes')
const prescriptionRoutes = require('./prescription.routes')
const drugRoutes = require('./drug.routes')
const financeRoutes = require('./finance.routes')
const dashboardRoutes = require('./dashboard.routes')
const settingRoutes = require('./setting.routes')
const staffRoutes = require('./staff.routes')
const adminRoutes = require('./admin.routes')
const notificationRoutes = require('./notification.routes')
const pushRoutes = require('./push.routes')
const uploadRoutes = require('./upload.routes')

const router = Router()

router.use('/auth', authRoutes)
router.use('/patients', patientRoutes)
router.use('/visits', visitRoutes)
router.use('/vitals', vitalsRoutes)
router.use('/admissions', admissionRoutes)
router.use('/activity', activityRoutes)
router.use('/investigations', investigationRoutes)
router.use('/prescriptions', prescriptionRoutes)
router.use('/drugs', drugRoutes)
router.use('/', financeRoutes)
router.use('/dashboard', dashboardRoutes)
router.use('/settings', settingRoutes)
router.use('/admin/staff', staffRoutes)
router.use('/admin', adminRoutes)
router.use('/notifications', notificationRoutes)
router.use('/push', pushRoutes)
router.use('/uploads', uploadRoutes)

module.exports = router
